import type { GalleryImage } from "@/types/galleryImageTypes";

export const galleryImages: GalleryImage[] = [
  { src: "/images/img1.jpg",      alt: "gallery.images.img1",              caption: "gallery.images.img1" },
  { src: "/images/img2.jpg",      alt: "gallery.images.img2",              caption: "gallery.images.img2" },
  { src: "/images/img3.jpg",      alt: "gallery.images.img3",              caption: "gallery.images.img3" },
  { src: "/images/img4.jpg",      alt: "gallery.images.img4",              caption: "gallery.images.img4" },
  { src: "/images/img6.jpg",      alt: "gallery.images.img6",              caption: "gallery.images.img6" },
  { src: "/images/img7.jpg",      alt: "gallery.images.img7",              caption: "gallery.images.img7" },
  { src: "/images/img9.jpg",      alt: "gallery.images.img9",              caption: "gallery.images.img9" },
  { src: "/images/img10.jpg",     alt: "gallery.images.img10",             caption: "gallery.images.img10" },
  { src: "/images/img11.jpg",     alt: "gallery.images.img11",             caption: "gallery.images.img11" },
  { src: "/images/img12.jpg",     alt: "gallery.images.img12",             caption: "gallery.images.img12" },
  { src: "/images/img13.jpg",     alt: "gallery.images.img13",             caption: "gallery.images.img13" },
  { src: "/images/img14.jpg",     alt: "gallery.images.img14",             caption: "gallery.images.img14" },
  { src: "/images/img15.jpg",     alt: "gallery.images.img15",             caption: "gallery.images.img15" },
  { src: "/images/img16.jpg",     alt: "gallery.images.img16",             caption: "gallery.images.img16" },
  { src: "/images/img17.jpg",     alt: "gallery.images.img17",             caption: "gallery.images.img17" },
  { src: "/images/img19.jpg",     alt: "gallery.images.img19",             caption: "gallery.images.img19" },
  { src: "/images/img20.jpg",     alt: "gallery.images.img20",             caption: "gallery.images.img20" },
  { src: "/images/img21.png",     alt: "gallery.images.img21",             caption: "gallery.images.img21" },
  { src: "/images/img22.jpg",     alt: "gallery.images.img22",             caption: "gallery.images.img22" },
  { src: "/images/img23.jpg",     alt: "gallery.images.img23",             caption: "gallery.images.img23" },
  { src: "/images/img24.jpg",     alt: "gallery.images.img24",             caption: "gallery.images.img24" },
  { src: "/images/img25.jpg",     alt: "gallery.images.img25",             caption: "gallery.images.img25" },
  { src: "/images/img26.jpg",     alt: "gallery.images.img26",             caption: "gallery.images.img26" },
  { src: "/images/img27.jpg",     alt: "gallery.images.img27",             caption: "gallery.images.img27" },
  { src: "/images/img28.jpg",     alt: "gallery.images.img28",             caption: "gallery.images.img28" },
  { src: "/images/montaz_1.jpg",  alt: "gallery.images.montaz1",           caption: "gallery.images.montaz1" },
  { src: "/images/montaz_2.jpg",  alt: "gallery.images.montaz2",           caption: "gallery.images.montaz2" },
  { src: "/images/montaz_3.jpg",  alt: "gallery.images.montaz3",           caption: "gallery.images.montaz3" },
  { src: "/images/montaz_4.jpg",  alt: "gallery.images.montaz4",           caption: "gallery.images.montaz4" },
  { src: "/images/montaz_5.jpg",  alt: "gallery.images.montaz5",           caption: "gallery.images.montaz5" },
  { src: "/images/new_img_1.jpg", alt: "gallery.images.newImg1",           caption: "gallery.images.newImg1" },
  { src: "/images/new_img_2.jpg", alt: "gallery.images.newImg2",           caption: "gallery.images.newImg2" },
  { src: "/images/new_img_3.jpg", alt: "gallery.images.newImg3",           caption: "gallery.images.newImg3" },
  { src: "/images/new_img_4.jpg", alt: "gallery.images.newImg4",           caption: "gallery.images.newImg4" },
  { src: "/images/new_img_5.jpg", alt: "gallery.images.newImg5",           caption: "gallery.images.newImg5" },
  { src: "/images/new_img_6.jpg", alt: "gallery.images.newImg6",           caption: "gallery.images.newImg6" },
  
];