import type { GalleryImage } from "@/types/galleryImageTypes";

export const galleryImages: GalleryImage[] = [
  { src: "/src/assets/images/img1.jpg",      alt: "Strojní výroba",                   caption: "Strojní výroba" },
  { src: "/src/assets/images/img2.jpg",      alt: "CNC obrábění",                     caption: "CNC obrábění" },
  { src: "/src/assets/images/img3.jpg",      alt: "Soustružení",                      caption: "Soustružení" },
  { src: "/src/assets/images/img4.jpg",      alt: "Frézování",                        caption: "Frézování" },
  { src: "/src/assets/images/img5.jpg",      alt: "Svařování",                        caption: "Svařování" },
  { src: "/src/assets/images/img6.jpg",      alt: "Výroba nosných konstrukcí",        caption: "Výroba nosných konstrukcí" },
  { src: "/src/assets/images/img7.jpg",      alt: "Výroba strojních součástí",        caption: "Výroba strojních součástí" },
  { src: "/src/assets/images/img8.jpg",      alt: "Výroba zemědělských strojů",       caption: "Výroba zemědělských strojů" },
  { src: "/src/assets/images/img9.jpg",      alt: "Výroba převodových skříní",        caption: "Výroba převodových skříní" },
  { src: "/src/assets/images/img10.jpg",     alt: "Energetické části – výměníky",     caption: "Energetické části – výměníky" },
  { src: "/src/assets/images/img11.jpg",     alt: "Výrobní hala",                     caption: "Výrobní hala" },
  { src: "/src/assets/images/img12.jpg",     alt: "Kontrola kvality",                 caption: "Kontrola kvality" },
  { src: "/src/assets/images/img13.jpg",     alt: "Hydraulický lis",                  caption: "Hydraulický lis" },
  { src: "/src/assets/images/img14.jpg",     alt: "Horizontální vyvrtávačka",         caption: "Horizontální vyvrtávačka" },
  { src: "/src/assets/images/img15.jpg",     alt: "Dokončovací práce",                caption: "Dokončovací práce" },
  { src: "/src/assets/images/montaz_1.jpg",  alt: "Montáž technologického celku",     caption: "Montáž technologického celku" },
  { src: "/src/assets/images/montaz_2.jpg",  alt: "Montáž a demontáž dílů",          caption: "Montáž a demontáž dílů" },
  { src: "/src/assets/images/montaz_3.jpg",  alt: "Montáž strojního zařízení",       caption: "Montáž strojního zařízení" },
  { src: "/src/assets/images/montaz_4.jpg",  alt: "Montáž v terénu",                 caption: "Montáž v terénu" },
  { src: "/src/assets/images/montaz_5.jpg",  alt: "Instalace technologie",            caption: "Instalace technologie" },
  { src: "/src/assets/images/montaz_6.jpg",  alt: "Finální montáž",                  caption: "Finální montáž" },
  { src: "/src/assets/images/montaz_7.jpg",  alt: "Přeprava a montáž",               caption: "Přeprava a montáž" },
  { src: "/src/assets/images/new_img_1.jpg", alt: "Výroba lopat a lžic",             caption: "Výroba lopat a lžic" },
  { src: "/src/assets/images/new_img_2.jpg", alt: "Hardoxové drtiče a násypky",      caption: "Hardoxové drtiče a násypky" },
  { src: "/src/assets/images/new_img_3.jpg", alt: "Výroba výklopných lžic",          caption: "Výroba výklopných lžic" },
  { src: "/src/assets/images/new_img_4.jpg", alt: "Potrubní systémy",                caption: "Potrubní systémy" },
  { src: "/src/assets/images/new_img_5.jpg", alt: "Trubkovnice a výměníky tepla",    caption: "Trubkovnice a výměníky tepla" },
  { src: "/src/assets/images/new_img_6.jpg", alt: "Renovace náhradních dílů",        caption: "Renovace náhradních dílů" },
  { src: "/src/assets/images/new_img_7.jpg", alt: "Zakázková výroba",                caption: "Zakázková výroba" },
  { src: "/src/assets/images/new_img_8.jpg", alt: "Sériová výroba součástí",         caption: "Sériová výroba součástí" },
];

